export const countries = [
  { id: 1, name: 'UAE', emoji: '🇦🇪', cities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { id: 2, name: 'France', emoji: '🇫🇷', cities: ['Paris', 'Nice', 'Lyon', 'Marseille'] },
  { id: 3, name: 'Japan', emoji: '🇯🇵', cities: ['Tokyo', 'Osaka', 'Kyoto', 'Hiroshima'] },
  { id: 4, name: 'USA', emoji: '🇺🇸', cities: ['New York', 'Los Angeles', 'Miami', 'Las Vegas', 'Chicago'] },
  { id: 5, name: 'Indonesia', emoji: '🇮🇩', cities: ['Bali', 'Jakarta', 'Lombok'] },
  { id: 6, name: 'UK', emoji: '🇬🇧', cities: ['London', 'Edinburgh', 'Manchester'] },
  { id: 7, name: 'Italy', emoji: '🇮🇹', cities: ['Rome', 'Venice', 'Florence', 'Milan'] },
  { id: 8, name: 'Spain', emoji: '🇪🇸', cities: ['Barcelona', 'Madrid', 'Seville', 'Valencia'] },
  { id: 9, name: 'Greece', emoji: '🇬🇷', cities: ['Athens', 'Santorini', 'Mykonos', 'Crete'] },
  { id: 10, name: 'Thailand', emoji: '🇹🇭', cities: ['Bangkok', 'Phuket', 'Chiang Mai', 'Krabi'] },
  { id: 11, name: 'Morocco', emoji: '🇲🇦', cities: ['Marrakech', 'Casablanca', 'Fes', 'Tangier', 'Agadir'] },
  { id: 12, name: 'Turkey', emoji: '🇹🇷', cities: ['Istanbul', 'Cappadocia', 'Antalya', 'Bodrum'] },
  { id: 13, name: 'Mexico', emoji: '🇲🇽', cities: ['Cancun', 'Mexico City', 'Tulum', 'Playa del Carmen'] },
  { id: 14, name: 'Australia', emoji: '🇦🇺', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Cairns'] },
  { id: 15, name: 'Brazil', emoji: '🇧🇷', cities: ['Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { id: 16, name: 'Portugal', emoji: '🇵🇹', cities: ['Lisbon', 'Porto', 'Algarve'] },
  { id: 17, name: 'Egypt', emoji: '🇪🇬', cities: ['Cairo', 'Luxor', 'Hurghada', 'Sharm El Sheikh'] },
  { id: 18, name: 'India', emoji: '🇮🇳', cities: ['Mumbai', 'Delhi', 'Goa', 'Jaipur', 'Agra'] },
  { id: 19, name: 'Maldives', emoji: '🇲🇻', cities: ['Malé', 'Maafushi', 'Baa Atoll'] },
  { id: 20, name: 'Switzerland', emoji: '🇨🇭', cities: ['Zurich', 'Geneva', 'Interlaken', 'Zermatt'] },
];

export const activities = [
  { id: 1, title: 'Desert Safari', city: 'Dubai', country: 'UAE', price: 89, rating: 4.9, duration: '6h', category: 'Adventure', emoji: '🐪', image: 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=800' },
  { id: 2, title: 'Eiffel Tower Tour', city: 'Paris', country: 'France', price: 65, rating: 4.8, duration: '3h', category: 'Tours', emoji: '🗼', image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800' },
  { id: 3, title: 'Surfing Lesson', city: 'Bali', country: 'Indonesia', price: 45, rating: 4.7, duration: '2h', category: 'Water', emoji: '🏄', image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800' },
  { id: 4, title: 'Colosseum Tour', city: 'Rome', country: 'Italy', price: 35, rating: 4.6, duration: '4h', category: 'Culture', emoji: '🏛️', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800' },
  { id: 5, title: 'Scuba Diving', city: 'Malé', country: 'Maldives', price: 120, rating: 5.0, duration: '3h', category: 'Water', emoji: '🤿', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800' },
  { id: 6, title: 'Santorini Sunset Cruise', city: 'Santorini', country: 'Greece', price: 75, rating: 4.9, duration: '2h', category: 'Tours', emoji: '🌅', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800' },
  { id: 7, title: 'Sushi Cooking Class', city: 'Tokyo', country: 'Japan', price: 55, rating: 4.8, duration: '3h', category: 'Food', emoji: '🍣', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800' },
  { id: 8, title: 'NYC Night Tour', city: 'New York', country: 'USA', price: 40, rating: 4.7, duration: '2h', category: 'Night', emoji: '🌆', image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800' },
  { id: 9, title: 'Sagrada Familia Tour', city: 'Barcelona', country: 'Spain', price: 30, rating: 4.8, duration: '2h', category: 'Culture', emoji: '⛪', image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800' },
  { id: 10, title: 'Marrakech Food Tour', city: 'Marrakech', country: 'Morocco', price: 35, rating: 4.9, duration: '4h', category: 'Food', emoji: '🥘', image: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800' },
  { id: 11, title: 'Cappadocia Hot Air Balloon', city: 'Cappadocia', country: 'Turkey', price: 150, rating: 5.0, duration: '2h', category: 'Adventure', emoji: '🎈', image: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800' },
  { id: 12, title: 'Pyramids Tour', city: 'Cairo', country: 'Egypt', price: 45, rating: 4.7, duration: '5h', category: 'Culture', emoji: '🏺', image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800' },
  { id: 13, title: 'Sydney Opera House Tour', city: 'Sydney', country: 'Australia', price: 40, rating: 4.6, duration: '2h', category: 'Culture', emoji: '🎭', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800' },
  { id: 14, title: 'Rio Carnival Experience', city: 'Rio de Janeiro', country: 'Brazil', price: 95, rating: 4.9, duration: '6h', category: 'Night', emoji: '🎉', image: 'https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=800' },
  { id: 15, title: 'Taj Mahal Sunrise Tour', city: 'Agra', country: 'India', price: 25, rating: 4.9, duration: '4h', category: 'Culture', emoji: '🕌', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800' },
  { id: 16, title: 'Swiss Alps Hiking', city: 'Interlaken', country: 'Switzerland', price: 110, rating: 4.8, duration: '8h', category: 'Adventure', emoji: '🏔️', image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800' },
  { id: 17, title: 'Fado Night Lisbon', city: 'Lisbon', country: 'Portugal', price: 50, rating: 4.7, duration: '3h', category: 'Night', emoji: '🎵', image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800' },
  { id: 18, title: 'Thai Cooking Class', city: 'Bangkok', country: 'Thailand', price: 40, rating: 4.8, duration: '4h', category: 'Food', emoji: '🍜', image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800' },
  { id: 19, title: 'Cancun Snorkeling', city: 'Cancun', country: 'Mexico', price: 55, rating: 4.7, duration: '3h', category: 'Water', emoji: '🐠', image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800' },
  { id: 20, title: 'Venice Gondola Ride', city: 'Venice', country: 'Italy', price: 80, rating: 4.8, duration: '1h', category: 'Tours', emoji: '🚣', image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800' },
];

export const categories = ['All', 'Tours', 'Adventure', 'Food', 'Culture', 'Water', 'Night'];