export const countries = [
  { id: 1, name: 'Afghanistan', emoji: '🇦🇫', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { id: 2, name: 'Albania', emoji: '🇦🇱', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { id: 3, name: 'Algeria', emoji: '🇩🇿', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { id: 4, name: 'Andorra', emoji: '🇦🇩', cities: ['Andorra la Vella', 'Escaldes-Engordany'] },
  { id: 5, name: 'Angola', emoji: '🇦🇴', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { id: 6, name: 'Argentina', emoji: '🇦🇷', cities: ['Buenos Aires', 'Mendoza', 'Bariloche', 'Iguazu Falls', 'Patagonia', 'Córdoba'] },
  { id: 7, name: 'Armenia', emoji: '🇦🇲', cities: ['Yerevan', 'Gyumri', 'Vanadzor'] },
  { id: 8, name: 'Australia', emoji: '🇦🇺', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Cairns', 'Perth', 'Gold Coast', 'Adelaide'] },
  { id: 9, name: 'Austria', emoji: '🇦🇹', cities: ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt', 'Graz'] },
  { id: 10, name: 'Azerbaijan', emoji: '🇦🇿', cities: ['Baku', 'Ganja', 'Sheki'] },
  { id: 11, name: 'Bahamas', emoji: '🇧🇸', cities: ['Nassau', 'Freeport', 'Paradise Island'] },
  { id: 12, name: 'Bahrain', emoji: '🇧🇭', cities: ['Manama', 'Muharraq', 'Riffa'] },
  { id: 13, name: 'Bangladesh', emoji: '🇧🇩', cities: ['Dhaka', 'Chittagong', "Cox's Bazar", 'Sylhet'] },
  { id: 14, name: 'Barbados', emoji: '🇧🇧', cities: ['Bridgetown', 'Speightstown', 'Oistins'] },
  { id: 15, name: 'Belarus', emoji: '🇧🇾', cities: ['Minsk', 'Brest', 'Grodno', 'Vitebsk'] },
  { id: 16, name: 'Belgium', emoji: '🇧🇪', cities: ['Brussels', 'Bruges', 'Ghent', 'Antwerp', 'Liège'] },
  { id: 17, name: 'Belize', emoji: '🇧🇿', cities: ['Belize City', 'San Ignacio', 'Ambergris Caye'] },
  { id: 18, name: 'Benin', emoji: '🇧🇯', cities: ['Cotonou', 'Porto-Novo', 'Parakou'] },
  { id: 19, name: 'Bhutan', emoji: '🇧🇹', cities: ['Thimphu', 'Paro', 'Punakha', 'Bumthang'] },
  { id: 20, name: 'Bolivia', emoji: '🇧🇴', cities: ['La Paz', 'Santa Cruz', 'Sucre', 'Uyuni Salt Flats', 'Potosí'] },
  { id: 21, name: 'Bosnia', emoji: '🇧🇦', cities: ['Sarajevo', 'Mostar', 'Banja Luka'] },
  { id: 22, name: 'Botswana', emoji: '🇧🇼', cities: ['Gaborone', 'Okavango Delta', 'Chobe'] },
  { id: 23, name: 'Brazil', emoji: '🇧🇷', cities: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Florianopolis', 'Iguazu Falls', 'Manaus', 'Recife'] },
  { id: 24, name: 'Brunei', emoji: '🇧🇳', cities: ['Bandar Seri Begawan', 'Seria', 'Kuala Belait'] },
  { id: 25, name: 'Bulgaria', emoji: '🇧🇬', cities: ['Sofia', 'Plovdiv', 'Varna', 'Sozopol'] },
  { id: 26, name: 'Burkina Faso', emoji: '🇧🇫', cities: ['Ouagadougou', 'Bobo-Dioulasso'] },
  { id: 27, name: 'Cambodia', emoji: '🇰🇭', cities: ['Siem Reap', 'Phnom Penh', 'Sihanoukville', 'Battambang'] },
  { id: 28, name: 'Cameroon', emoji: '🇨🇲', cities: ['Yaoundé', 'Douala', 'Bamenda'] },
  { id: 29, name: 'Canada', emoji: '🇨🇦', cities: ['Toronto', 'Vancouver', 'Montreal', 'Quebec City', 'Banff', 'Calgary', 'Ottawa', 'Victoria'] },
  { id: 30, name: 'Chile', emoji: '🇨🇱', cities: ['Santiago', 'Valparaíso', 'Atacama Desert', 'Patagonia', 'Easter Island'] },
  { id: 31, name: 'China', emoji: '🇨🇳', cities: ['Beijing', 'Shanghai', "Xi'an", 'Guilin', 'Chengdu', 'Hong Kong', 'Macau', 'Zhangjiajie'] },
  { id: 32, name: 'Colombia', emoji: '🇨🇴', cities: ['Bogota', 'Medellin', 'Cartagena', 'Santa Marta', 'Cali'] },
  { id: 33, name: 'Congo', emoji: '🇨🇩', cities: ['Kinshasa', 'Lubumbashi', 'Goma'] },
  { id: 34, name: 'Costa Rica', emoji: '🇨🇷', cities: ['San José', 'Manuel Antonio', 'Arenal', 'Monteverde', 'Tamarindo'] },
  { id: 35, name: 'Croatia', emoji: '🇭🇷', cities: ['Dubrovnik', 'Split', 'Zagreb', 'Hvar', 'Plitvice Lakes', 'Rovinj'] },
  { id: 36, name: 'Cuba', emoji: '🇨🇺', cities: ['Havana', 'Trinidad', 'Varadero', 'Santiago de Cuba'] },
  { id: 37, name: 'Cyprus', emoji: '🇨🇾', cities: ['Nicosia', 'Limassol', 'Paphos', 'Ayia Napa'] },
  { id: 38, name: 'Czech Republic', emoji: '🇨🇿', cities: ['Prague', 'Brno', 'Český Krumlov', 'Karlovy Vary'] },
  { id: 39, name: 'Denmark', emoji: '🇩🇰', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { id: 40, name: 'Dominican Republic', emoji: '🇩🇴', cities: ['Santo Domingo', 'Punta Cana', 'Puerto Plata', 'Samaná'] },
  { id: 41, name: 'Ecuador', emoji: '🇪🇨', cities: ['Quito', 'Guayaquil', 'Galápagos Islands', 'Cuenca'] },
  { id: 42, name: 'Egypt', emoji: '🇪🇬', cities: ['Cairo', 'Luxor', 'Hurghada', 'Sharm El Sheikh', 'Alexandria', 'Aswan'] },
  { id: 43, name: 'El Salvador', emoji: '🇸🇻', cities: ['San Salvador', 'Santa Ana', 'El Tunco'] },
  { id: 44, name: 'Estonia', emoji: '🇪🇪', cities: ['Tallinn', 'Tartu', 'Pärnu'] },
  { id: 45, name: 'Ethiopia', emoji: '🇪🇹', cities: ['Addis Ababa', 'Lalibela', 'Gondar', 'Axum'] },
  { id: 46, name: 'Fiji', emoji: '🇫🇯', cities: ['Suva', 'Nadi', 'Mamanuca Islands', 'Yasawa Islands'] },
  { id: 47, name: 'Finland', emoji: '🇫🇮', cities: ['Helsinki', 'Rovaniemi', 'Tampere', 'Turku'] },
  { id: 48, name: 'France', emoji: '🇫🇷', cities: ['Paris', 'Nice', 'Lyon', 'Marseille', 'Bordeaux', 'Strasbourg', 'Versailles', 'Mont Saint-Michel'] },
  { id: 49, name: 'Georgia', emoji: '🇬🇪', cities: ['Tbilisi', 'Batumi', 'Kazbegi', 'Kutaisi'] },
  { id: 50, name: 'Germany', emoji: '🇩🇪', cities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Heidelberg', 'Neuschwanstein', 'Dresden'] },
  { id: 51, name: 'Ghana', emoji: '🇬🇭', cities: ['Accra', 'Kumasi', 'Cape Coast', 'Tamale'] },
  { id: 52, name: 'Greece', emoji: '🇬🇷', cities: ['Athens', 'Santorini', 'Mykonos', 'Crete', 'Rhodes', 'Corfu', 'Thessaloniki'] },
  { id: 53, name: 'Guatemala', emoji: '🇬🇹', cities: ['Guatemala City', 'Antigua', 'Lake Atitlán', 'Tikal'] },
  { id: 54, name: 'Honduras', emoji: '🇭🇳', cities: ['Tegucigalpa', 'Roatán', 'Copán'] },
  { id: 55, name: 'Hungary', emoji: '🇭🇺', cities: ['Budapest', 'Debrecen', 'Pécs', 'Eger', 'Győr'] },
  { id: 56, name: 'Iceland', emoji: '🇮🇸', cities: ['Reykjavik', 'Golden Circle', 'Blue Lagoon', 'Northern Lights Tour', 'Akureyri'] },
  { id: 57, name: 'India', emoji: '🇮🇳', cities: ['Mumbai', 'Delhi', 'Goa', 'Jaipur', 'Agra', 'Kerala', 'Varanasi', 'Udaipur', 'Kolkata', 'Chennai'] },
  { id: 58, name: 'Indonesia', emoji: '🇮🇩', cities: ['Bali', 'Jakarta', 'Lombok', 'Yogyakarta', 'Komodo', 'Raja Ampat'] },
  { id: 59, name: 'Iran', emoji: '🇮🇷', cities: ['Tehran', 'Isfahan', 'Shiraz', 'Yazd', 'Persepolis'] },
  { id: 60, name: 'Iraq', emoji: '🇮🇶', cities: ['Baghdad', 'Erbil', 'Basra', 'Najaf'] },
  { id: 61, name: 'Ireland', emoji: '🇮🇪', cities: ['Dublin', 'Galway', 'Cork', 'Killarney', 'Cliffs of Moher'] },
  { id: 62, name: 'Israel', emoji: '🇮🇱', cities: ['Jerusalem', 'Tel Aviv', 'Eilat', 'Haifa', 'Dead Sea', 'Nazareth'] },
  { id: 63, name: 'Italy', emoji: '🇮🇹', cities: ['Rome', 'Venice', 'Florence', 'Milan', 'Naples', 'Amalfi', 'Sicily', 'Cinque Terre', 'Tuscany'] },
  { id: 64, name: 'Jamaica', emoji: '🇯🇲', cities: ['Kingston', 'Montego Bay', 'Negril', 'Ocho Rios'] },
  { id: 65, name: 'Japan', emoji: '🇯🇵', cities: ['Tokyo', 'Osaka', 'Kyoto', 'Hiroshima', 'Nara', 'Sapporo', 'Fukuoka', 'Hakone', 'Nikko'] },
  { id: 66, name: 'Jordan', emoji: '🇯🇴', cities: ['Amman', 'Petra', 'Wadi Rum', 'Aqaba', 'Dead Sea'] },
  { id: 67, name: 'Kazakhstan', emoji: '🇰🇿', cities: ['Almaty', 'Nur-Sultan', 'Shymkent'] },
  { id: 68, name: 'Kenya', emoji: '🇰🇪', cities: ['Nairobi', 'Maasai Mara', 'Mombasa', 'Amboseli', 'Diani Beach', 'Lamu'] },
  { id: 69, name: 'Kuwait', emoji: '🇰🇼', cities: ['Kuwait City', 'Salmiya', 'Hawalli'] },
  { id: 70, name: 'Kyrgyzstan', emoji: '🇰🇬', cities: ['Bishkek', 'Osh', 'Karakol', 'Song-Kul Lake'] },
  { id: 71, name: 'Laos', emoji: '🇱🇦', cities: ['Luang Prabang', 'Vientiane', 'Vang Vieng', 'Pakse'] },
  { id: 72, name: 'Latvia', emoji: '🇱🇻', cities: ['Riga', 'Jurmala', 'Sigulda', 'Cesis'] },
  { id: 73, name: 'Lebanon', emoji: '🇱🇧', cities: ['Beirut', 'Byblos', 'Tripoli', 'Baalbek'] },
  { id: 74, name: 'Lithuania', emoji: '🇱🇹', cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Trakai'] },
  { id: 75, name: 'Luxembourg', emoji: '🇱🇺', cities: ['Luxembourg City', 'Esch-sur-Alzette'] },
  { id: 76, name: 'Madagascar', emoji: '🇲🇬', cities: ['Antananarivo', 'Nosy Be', 'Morondava', 'Ifaty'] },
  { id: 77, name: 'Malaysia', emoji: '🇲🇾', cities: ['Kuala Lumpur', 'Penang', 'Langkawi', 'Borneo', 'Malacca', 'Cameron Highlands'] },
  { id: 78, name: 'Maldives', emoji: '🇲🇻', cities: ['Malé', 'Maafushi', 'Baa Atoll', 'North Malé Atoll', 'South Malé Atoll', 'Ari Atoll'] },
  { id: 79, name: 'Malta', emoji: '🇲🇹', cities: ['Valletta', 'Mdina', 'Sliema', 'Gozo'] },
  { id: 80, name: 'Mexico', emoji: '🇲🇽', cities: ['Cancun', 'Mexico City', 'Tulum', 'Playa del Carmen', 'Oaxaca', 'Cabo San Lucas', 'Guadalajara', 'Mérida'] },
  { id: 81, name: 'Moldova', emoji: '🇲🇩', cities: ['Chișinău', 'Tiraspol', 'Orheiul Vechi'] },
  { id: 82, name: 'Monaco', emoji: '🇲🇨', cities: ['Monte Carlo', 'Monaco-Ville'] },
  { id: 83, name: 'Mongolia', emoji: '🇲🇳', cities: ['Ulaanbaatar', 'Gobi Desert', 'Khövsgöl Lake'] },
  { id: 84, name: 'Montenegro', emoji: '🇲🇪', cities: ['Kotor', 'Budva', 'Podgorica', 'Durmitor'] },
  { id: 85, name: 'Morocco', emoji: '🇲🇦', cities: ['Marrakech', 'Casablanca', 'Fes', 'Tangier', 'Agadir', 'Chefchaouen', 'Essaouira', 'Rabat', 'Meknes', 'Merzouga'] },
  { id: 86, name: 'Mozambique', emoji: '🇲🇿', cities: ['Maputo', 'Bazaruto Archipelago', 'Pemba'] },
  { id: 87, name: 'Myanmar', emoji: '🇲🇲', cities: ['Yangon', 'Bagan', 'Mandalay', 'Inle Lake'] },
  { id: 88, name: 'Namibia', emoji: '🇳🇦', cities: ['Windhoek', 'Sossusvlei', 'Etosha', 'Swakopmund'] },
  { id: 89, name: 'Nepal', emoji: '🇳🇵', cities: ['Kathmandu', 'Pokhara', 'Everest Base Camp', 'Chitwan', 'Lumbini'] },
  { id: 90, name: 'Netherlands', emoji: '🇳🇱', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Keukenhof'] },
  { id: 91, name: 'New Zealand', emoji: '🇳🇿', cities: ['Auckland', 'Queenstown', 'Christchurch', 'Wellington', 'Rotorua', 'Milford Sound'] },
  { id: 92, name: 'Nicaragua', emoji: '🇳🇮', cities: ['Managua', 'Granada', 'León', 'Ometepe Island'] },
  { id: 93, name: 'Nigeria', emoji: '🇳🇬', cities: ['Lagos', 'Abuja', 'Kano', 'Port Harcourt'] },
  { id: 94, name: 'North Macedonia', emoji: '🇲🇰', cities: ['Skopje', 'Ohrid', 'Bitola'] },
  { id: 95, name: 'Norway', emoji: '🇳🇴', cities: ['Oslo', 'Bergen', 'Fjords', 'Tromsø', 'Lofoten Islands', 'Stavanger'] },
  { id: 96, name: 'Oman', emoji: '🇴🇲', cities: ['Muscat', 'Salalah', 'Nizwa', 'Wahiba Sands'] },
  { id: 97, name: 'Pakistan', emoji: '🇵🇰', cities: ['Lahore', 'Karachi', 'Islamabad', 'Hunza Valley', 'Swat Valley'] },
  { id: 98, name: 'Panama', emoji: '🇵🇦', cities: ['Panama City', 'Bocas del Toro', 'Boquete', 'San Blas Islands'] },
  { id: 99, name: 'Paraguay', emoji: '🇵🇾', cities: ['Asunción', 'Ciudad del Este', 'Encarnación'] },
  { id: 100, name: 'Peru', emoji: '🇵🇪', cities: ['Lima', 'Cusco', 'Machu Picchu', 'Arequipa', 'Lake Titicaca', 'Amazon'] },
  { id: 101, name: 'Philippines', emoji: '🇵🇭', cities: ['Manila', 'Palawan', 'Boracay', 'Cebu', 'Siargao', 'Bohol'] },
  { id: 102, name: 'Poland', emoji: '🇵🇱', cities: ['Warsaw', 'Krakow', 'Gdansk', 'Wroclaw', 'Zakopane'] },
  { id: 103, name: 'Portugal', emoji: '🇵🇹', cities: ['Lisbon', 'Porto', 'Algarve', 'Sintra', 'Madeira', 'Azores', 'Óbidos'] },
  { id: 104, name: 'Qatar', emoji: '🇶🇦', cities: ['Doha', 'Al Wakrah', 'Lusail'] },
  { id: 105, name: 'Romania', emoji: '🇷🇴', cities: ['Bucharest', 'Transylvania', 'Brasov', 'Sibiu', 'Cluj-Napoca'] },
  { id: 106, name: 'Russia', emoji: '🇷🇺', cities: ['Moscow', 'Saint Petersburg', 'Lake Baikal', 'Kazan', 'Sochi'] },
  { id: 107, name: 'Rwanda', emoji: '🇷🇼', cities: ['Kigali', 'Volcanoes National Park', 'Lake Kivu'] },
  { id: 108, name: 'Saudi Arabia', emoji: '🇸🇦', cities: ['Riyadh', 'Jeddah', 'AlUla', 'NEOM', 'Diriyah', 'Mecca'] },
  { id: 109, name: 'Senegal', emoji: '🇸🇳', cities: ['Dakar', 'Saint-Louis', 'Casamance', 'Sine Saloum'] },
  { id: 110, name: 'Serbia', emoji: '🇷🇸', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Zlatibor'] },
  { id: 111, name: 'Singapore', emoji: '🇸🇬', cities: ['Singapore City', 'Sentosa Island', 'Gardens by the Bay', 'Marina Bay'] },
  { id: 112, name: 'Slovakia', emoji: '🇸🇰', cities: ['Bratislava', 'Košice', 'High Tatras', 'Banská Štiavnica'] },
  { id: 113, name: 'Slovenia', emoji: '🇸🇮', cities: ['Ljubljana', 'Lake Bled', 'Piran', 'Postojna Cave'] },
  { id: 114, name: 'South Africa', emoji: '🇿🇦', cities: ['Cape Town', 'Johannesburg', 'Durban', 'Safari Parks', 'Garden Route', 'Kruger National Park'] },
  { id: 115, name: 'South Korea', emoji: '🇰🇷', cities: ['Seoul', 'Busan', 'Jeju Island', 'Gyeongju', 'Incheon'] },
  { id: 116, name: 'Spain', emoji: '🇪🇸', cities: ['Barcelona', 'Madrid', 'Seville', 'Valencia', 'Granada', 'Ibiza', 'Mallorca', 'San Sebastián', 'Toledo'] },
  { id: 117, name: 'Sri Lanka', emoji: '🇱🇰', cities: ['Colombo', 'Kandy', 'Galle', 'Sigiriya', 'Ella', 'Trincomalee'] },
  { id: 118, name: 'Sweden', emoji: '🇸🇪', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Kiruna'] },
  { id: 119, name: 'Switzerland', emoji: '🇨🇭', cities: ['Zurich', 'Geneva', 'Interlaken', 'Zermatt', 'Lucerne', 'Bern', 'Lugano'] },
  { id: 120, name: 'Taiwan', emoji: '🇹🇼', cities: ['Taipei', 'Kaohsiung', 'Tainan', 'Taroko Gorge', 'Sun Moon Lake'] },
  { id: 121, name: 'Tanzania', emoji: '🇹🇿', cities: ['Zanzibar', 'Serengeti', 'Kilimanjaro', 'Dar es Salaam', 'Ngorongoro'] },
  { id: 122, name: 'Thailand', emoji: '🇹🇭', cities: ['Bangkok', 'Phuket', 'Chiang Mai', 'Krabi', 'Koh Samui', 'Pattaya', 'Pai', 'Koh Phi Phi'] },
  { id: 123, name: 'Tunisia', emoji: '🇹🇳', cities: ['Tunis', 'Carthage', 'Sidi Bou Said', 'Djerba', 'Sousse'] },
  { id: 124, name: 'Turkey', emoji: '🇹🇷', cities: ['Istanbul', 'Cappadocia', 'Antalya', 'Bodrum', 'Izmir', 'Pamukkale', 'Ephesus'] },
  { id: 125, name: 'Uganda', emoji: '🇺🇬', cities: ['Kampala', 'Bwindi', 'Queen Elizabeth National Park'] },
  { id: 126, name: 'UAE', emoji: '🇦🇪', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah'] },
  { id: 127, name: 'UK', emoji: '🇬🇧', cities: ['London', 'Edinburgh', 'Manchester', 'Liverpool', 'Oxford', 'Bath', 'Cambridge', 'York', 'Brighton'] },
  { id: 128, name: 'Ukraine', emoji: '🇺🇦', cities: ['Kyiv', 'Lviv', 'Odessa', 'Kharkiv'] },
  { id: 129, name: 'Uruguay', emoji: '🇺🇾', cities: ['Montevideo', 'Punta del Este', 'Colonia del Sacramento'] },
  { id: 130, name: 'USA', emoji: '🇺🇸', cities: ['New York', 'Los Angeles', 'Miami', 'Las Vegas', 'Chicago', 'San Francisco', 'New Orleans', 'Hawaii', 'Washington DC', 'Boston', 'Nashville', 'Denver'] },
  { id: 131, name: 'Uzbekistan', emoji: '🇺🇿', cities: ['Samarkand', 'Bukhara', 'Tashkent', 'Khiva'] },
  { id: 132, name: 'Venezuela', emoji: '🇻🇪', cities: ['Caracas', 'Mérida', 'Angel Falls', 'Los Roques'] },
  { id: 133, name: 'Vietnam', emoji: '🇻🇳', cities: ['Ho Chi Minh City', 'Hanoi', 'Hoi An', 'Ha Long Bay', 'Da Nang', 'Hue', 'Sapa'] },
  { id: 134, name: 'Yemen', emoji: '🇾🇪', cities: ['Socotra Island', "Sana'a", 'Aden'] },
  { id: 135, name: 'Zambia', emoji: '🇿🇲', cities: ['Lusaka', 'Victoria Falls', 'South Luangwa'] },
  { id: 136, name: 'Zimbabwe', emoji: '🇿🇼', cities: ['Harare', 'Victoria Falls', 'Hwange', 'Great Zimbabwe'] },
  { id: 137, name: 'Kosovo', emoji: '🇽🇰', cities: ['Pristina', 'Prizren', 'Peja'] },
  { id: 138, name: 'Palestine', emoji: '🇵🇸', cities: ['Ramallah', 'Bethlehem', 'Jericho', 'Nablus'] },
  { id: 139, name: 'Cuba', emoji: '🇨🇺', cities: ['Havana', 'Trinidad', 'Varadero', 'Santiago de Cuba', 'Viñales'] },
  { id: 140, name: 'Haiti', emoji: '🇭🇹', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Jacmel'] },
  { id: 141, name: 'Papua New Guinea', emoji: '🇵🇬', cities: ['Port Moresby', 'Lae', 'Goroka'] },
  { id: 142, name: 'Sudan', emoji: '🇸🇩', cities: ['Khartoum', 'Meroe Pyramids', 'Port Sudan'] },
  { id: 143, name: 'Libya', emoji: '🇱🇾', cities: ['Tripoli', 'Benghazi', 'Leptis Magna'] },
  { id: 144, name: 'Somalia', emoji: '🇸🇴', cities: ['Mogadishu', 'Hargeisa', 'Bosaso'] },
  { id: 145, name: 'Eritrea', emoji: '🇪🇷', cities: ['Asmara', 'Massawa', 'Keren'] },
  { id: 146, name: 'Cabo Verde', emoji: '🇨🇻', cities: ['Praia', 'Mindelo', 'Santa Maria', 'São Filipe'] },
  { id: 147, name: 'Comoros', emoji: '🇰🇲', cities: ['Moroni', 'Mutsamudu', 'Fomboni'] },
  { id: 148, name: 'Djibouti', emoji: '🇩🇯', cities: ['Djibouti City', 'Tadjoura', 'Obock'] },
  { id: 149, name: 'Equatorial Guinea', emoji: '🇬🇶', cities: ['Malabo', 'Bata', 'Ebebiyín'] },
  { id: 150, name: 'Gabon', emoji: '🇬🇦', cities: ['Libreville', 'Port-Gentil', 'Lopé National Park'] },
  { id: 151, name: 'Gambia', emoji: '🇬🇲', cities: ['Banjul', 'Serrekunda', 'Bakau'] },
  { id: 152, name: 'Guinea', emoji: '🇬🇳', cities: ['Conakry', 'Kindia', 'Labé'] },
  { id: 153, name: 'Guinea-Bissau', emoji: '🇬🇼', cities: ['Bissau', 'Bafatá', 'Cacheu'] },
  { id: 154, name: 'Ivory Coast', emoji: '🇨🇮', cities: ['Abidjan', 'Yamoussoukro', 'Bouaké'] },
  { id: 155, name: 'Lesotho', emoji: '🇱🇸', cities: ['Maseru', 'Teyateyaneng', 'Malealea'] },
  { id: 156, name: 'Liberia', emoji: '🇱🇷', cities: ['Monrovia', 'Gbarnga', 'Buchanan'] },
  { id: 157, name: 'Malawi', emoji: '🇲🇼', cities: ['Lilongwe', 'Blantyre', 'Lake Malawi'] },
  { id: 158, name: 'Mali', emoji: '🇲🇱', cities: ['Bamako', 'Timbuktu', 'Djenné', 'Mopti'] },
  { id: 159, name: 'Mauritania', emoji: '🇲🇷', cities: ['Nouakchott', 'Chinguetti', 'Ouadane'] },
  { id: 160, name: 'Mauritius', emoji: '🇲🇺', cities: ['Port Louis', 'Grand Baie', 'Flic en Flac', 'Belle Mare'] },
  { id: 161, name: 'Niger', emoji: '🇳🇪', cities: ['Niamey', 'Agadez', 'Zinder'] },
  { id: 162, name: 'Reunion', emoji: '🇷🇪', cities: ['Saint-Denis', 'Saint-Pierre', 'Cilaos', 'Piton de la Fournaise'] },
  { id: 163, name: 'São Tomé', emoji: '🇸🇹', cities: ['São Tomé', 'Santo António'] },
  { id: 164, name: 'Seychelles', emoji: '🇸🇨', cities: ['Victoria', 'Praslin', 'La Digue', 'Mahé'] },
  { id: 165, name: 'Sierra Leone', emoji: '🇸🇱', cities: ['Freetown', 'Bo', 'Banana Islands'] },
  { id: 166, name: 'Togo', emoji: '🇹🇬', cities: ['Lomé', 'Kpalimé', 'Atakpamé'] },
  { id: 167, name: 'Central African Republic', emoji: '🇨🇫', cities: ['Bangui', 'Dzanga-Sangha'] },
  { id: 168, name: 'South Sudan', emoji: '🇸🇸', cities: ['Juba', 'Wau', 'Malakal'] },
  { id: 169, name: 'Eswatini', emoji: '🇸🇿', cities: ['Mbabane', 'Manzini', 'Hlane Royal National Park'] },
  { id: 170, name: 'Burundi', emoji: '🇧🇮', cities: ['Bujumbura', 'Gitega', 'Lake Tanganyika'] },
  { id: 171, name: 'Timor-Leste', emoji: '🇹🇱', cities: ['Dili', 'Baucau', 'Atauro Island'] },
  { id: 172, name: 'Turkmenistan', emoji: '🇹🇲', cities: ['Ashgabat', 'Darvaza Gas Crater', 'Merv'] },
  { id: 173, name: 'Tajikistan', emoji: '🇹🇯', cities: ['Dushanbe', 'Pamir Highway', 'Iskanderkul Lake'] },
  { id: 174, name: 'Tonga', emoji: '🇹🇴', cities: ['Nukuʻalofa', 'Vavaʻu', 'Ha\'apai'] },
  { id: 175, name: 'Samoa', emoji: '🇼🇸', cities: ['Apia', 'Savaiʻi', 'To Sua Ocean Trench'] },
  { id: 176, name: 'Solomon Islands', emoji: '🇸🇧', cities: ['Honiara', 'Gizo', 'Munda'] },
  { id: 177, name: 'Vanuatu', emoji: '🇻🇺', cities: ['Port Vila', 'Luganville', 'Tanna Island'] },
  { id: 178, name: 'Palau', emoji: '🇵🇼', cities: ['Ngerulmud', 'Koror', 'Rock Islands'] },
  { id: 179, name: 'Micronesia', emoji: '🇫🇲', cities: ['Palikir', 'Weno', 'Pohnpei'] },
  { id: 180, name: 'Marshall Islands', emoji: '🇲🇭', cities: ['Majuro', 'Ebeye', 'Bikini Atoll'] },
  { id: 181, name: 'Kiribati', emoji: '🇰🇮', cities: ['South Tarawa', 'Betio', 'Christmas Island'] },
  { id: 182, name: 'Nauru', emoji: '🇳🇷', cities: ['Yaren', 'Aiwo', 'Boe'] },
  { id: 183, name: 'Tuvalu', emoji: '🇹🇻', cities: ['Funafuti', 'Nanumea', 'Vaitupu'] },
  { id: 184, name: 'Cook Islands', emoji: '🇨🇰', cities: ['Avarua', 'Muri Beach', 'Aitutaki'] },
  { id: 185, name: 'Suriname', emoji: '🇸🇷', cities: ['Paramaribo', 'Brownsberg', 'Galibi'] },
  { id: 186, name: 'Guyana', emoji: '🇬🇾', cities: ['Georgetown', 'Kaieteur Falls', 'Rupununi'] },
  { id: 187, name: 'Trinidad and Tobago', emoji: '🇹🇹', cities: ['Port of Spain', 'San Fernando', 'Tobago'] },
  { id: 188, name: 'Grenada', emoji: '🇬🇩', cities: ['St. George\'s', 'Grand Anse', 'Carriacou'] },
  { id: 189, name: 'Saint Lucia', emoji: '🇱🇨', cities: ['Castries', 'Soufrière', 'Gros Islet'] },
  { id: 190, name: 'Barbados', emoji: '🇧🇧', cities: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba'] },
  { id: 191, name: 'Antigua', emoji: '🇦🇬', cities: ['St. John\'s', 'English Harbour', 'Jolly Harbour'] },
  { id: 192, name: 'Saint Kitts', emoji: '🇰🇳', cities: ['Basseterre', 'Charlestown', 'Sandy Point'] },
  { id: 193, name: 'Dominica', emoji: '🇩🇲', cities: ['Roseau', 'Portsmouth', 'Boiling Lake'] },
  { id: 194, name: 'Saint Vincent', emoji: '🇻🇨', cities: ['Kingstown', 'Bequia', 'Mustique'] },
  { id: 195, name: 'Liechtenstein', emoji: '🇱🇮', cities: ['Vaduz', 'Schaan', 'Balzers'] },
];

export const activities = [
  { id: 1, title: 'Desert Safari', city: 'Dubai', country: 'UAE', price: 89, rating: 4.9, duration: '6h', category: 'Adventure', emoji: '🐪', image: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=800' },
  { id: 2, title: 'Eiffel Tower Tour', city: 'Paris', country: 'France', price: 65, rating: 4.8, duration: '3h', category: 'Tours', emoji: '🗼', image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800' },
  { id: 4, title: 'Colosseum Tour', city: 'Rome', country: 'Italy', price: 35, rating: 4.6, duration: '4h', category: 'Culture', emoji: '🏛️', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800' },
  { id: 5, title: 'Scuba Diving', city: 'Malé', country: 'Maldives', price: 120, rating: 5.0, duration: '3h', category: 'Water', emoji: '🤿', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800' },
  { id: 6, title: 'Santorini Sunset Cruise', city: 'Santorini', country: 'Greece', price: 75, rating: 4.9, duration: '2h', category: 'Tours', emoji: '🌅', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800' },
  { id: 7, title: 'Sushi Cooking Class', city: 'Tokyo', country: 'Japan', price: 55, rating: 4.8, duration: '3h', category: 'Food', emoji: '🍣', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800' },
  { id: 8, title: 'NYC Night Tour', city: 'New York', country: 'USA', price: 40, rating: 4.7, duration: '2h', category: 'Night', emoji: '🌆', image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800' },
  { id: 9, title: 'Sagrada Familia Tour', city: 'Barcelona', country: 'Spain', price: 30, rating: 4.8, duration: '2h', category: 'Culture', emoji: '⛪', image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800' },
  { id: 10, title: 'Marrakech Food Tour', city: 'Marrakech', country: 'Morocco', price: 35, rating: 4.9, duration: '4h', category: 'Food', emoji: '🥘', image: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800' },
  { id: 11, title: 'Cappadocia Hot Air Balloon', city: 'Cappadocia', country: 'Turkey', price: 150, rating: 5.0, duration: '2h', category: 'Adventure', emoji: '🎈', image: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800' },
  { id: 12, title: 'Pyramids Tour', city: 'Cairo', country: 'Egypt', price: 45, rating: 4.7, duration: '5h', category: 'Culture', emoji: '🏺', image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800' },
  { id: 13, title: 'Sydney Opera House Tour', city: 'Sydney', country: 'Australia', price: 40, rating: 4.6, duration: '2h', category: 'Culture', emoji: '🎭', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800' },
  { id: 14, title: 'Rio Carnival Experience', city: 'Rio de Janeiro', country: 'Brazil', price: 95, rating: 4.9, duration: '6h', category: 'Night', emoji: '🎉', image: 'https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=800' },
  { id: 15, title: 'Taj Mahal Sunrise Tour', city: 'Agra', country: 'India', price: 25, rating: 4.9, duration: '4h', category: 'Culture', emoji: '🕌', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800' },
  { id: 16, title: 'Swiss Alps Hiking', city: 'Interlaken', country: 'Switzerland', price: 110, rating: 4.8, duration: '8h', category: 'Adventure', emoji: '🏔️', image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800' },
  { id: 17, title: 'Fado Night Lisbon', city: 'Lisbon', country: 'Portugal', price: 50, rating: 4.7, duration: '3h', category: 'Night', emoji: '🎵', image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800' },
  { id: 18, title: 'Thai Cooking Class', city: 'Bangkok', country: 'Thailand', price: 40, rating: 4.8, duration: '4h', category: 'Food', emoji: '🍜', image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800' },
  { id: 19, title: 'Cancun Snorkeling', city: 'Cancun', country: 'Mexico', price: 55, rating: 4.7, duration: '3h', category: 'Water', emoji: '🐠', image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800' },
  { id: 20, title: 'Venice Gondola Ride', city: 'Venice', country: 'Italy', price: 80, rating: 4.8, duration: '1h', category: 'Tours', emoji: '🚣', image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800' },
  { id: 21, title: 'Petra Night Tour', city: 'Petra', country: 'Jordan', price: 60, rating: 4.9, duration: '3h', category: 'Culture', emoji: '🏜️', image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800' },
  { id: 22, title: 'Maasai Mara Safari', city: 'Maasai Mara', country: 'Kenya', price: 200, rating: 5.0, duration: '8h', category: 'Adventure', emoji: '🦁', image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800' },
  { id: 23, title: 'Northern Lights Tour', city: 'Tromsø', country: 'Norway', price: 130, rating: 4.9, duration: '4h', category: 'Adventure', emoji: '🌌', image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800' },
  { id: 24, title: 'Dubrovnik City Walls', city: 'Dubrovnik', country: 'Croatia', price: 25, rating: 4.8, duration: '2h', category: 'Culture', emoji: '🏰', image: 'https://images.unsplash.com/photo-1555990793-da11153b6ec9?w=800' },
  { id: 25, title: 'Singapore Night Safari', city: 'Singapore City', country: 'Singapore', price: 70, rating: 4.7, duration: '3h', category: 'Night', emoji: '🦒', image: 'https://images.unsplash.com/photo-1508964942454-1a56651d54ac?w=800' },
  { id: 26, title: 'Zanzibar Spice Tour', city: 'Zanzibar', country: 'Tanzania', price: 45, rating: 4.8, duration: '4h', category: 'Food', emoji: '🌶️', image: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800' },
  { id: 27, title: 'Machu Picchu Trek', city: 'Cusco', country: 'Peru', price: 180, rating: 5.0, duration: '8h', category: 'Adventure', emoji: '🏔️', image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800' },
  { id: 28, title: 'Ha Long Bay Cruise', city: 'Ha Long Bay', country: 'Vietnam', price: 120, rating: 4.9, duration: '8h', category: 'Tours', emoji: '⛵', image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800' },
  { id: 29, title: 'Prague Castle Tour', city: 'Prague', country: 'Czech Republic', price: 30, rating: 4.7, duration: '3h', category: 'Culture', emoji: '🏰', image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800' },
  { id: 30, title: 'Budapest Thermal Baths', city: 'Budapest', country: 'Hungary', price: 35, rating: 4.8, duration: '3h', category: 'Water', emoji: '♨️', image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800' },
];

export const categories = ['All', 'Tours', 'Adventure', 'Food', 'Culture', 'Water', 'Night'];